### ISSUE TITLE
unable to compile on mbedtls 3.6+

### ISSUE THREAD

**Issue by orangepizza** [warmcat/libwebsockets#3127]
mbedtls_x509_get_name become unexposed in mbedtls 3.6, make it blocking compile
made a temp fix by redeclare moved function in a file, but will need actual alternative implementation  where it actually used
https://github.com/openwrt/packages/pull/24071

**Comment by dddaniel** [comment]
Can confirm. Won't build without -DDISABLE_WERROR=ON 

`[ 30%] Building C object lib/CMakeFiles/websockets_shared.dir/tls/mbedtls/mbedtls-client.c.o
[ 30%] Building C object lib/CMakeFiles/websockets.dir/tls/mbedtls/mbedtls-server.c.o
/home/daniel/srcs/libwebsockets/lib/tls/mbedtls/mbedtls-extensions.c: In function ‘lws_mbedtls_x509_parse_general_name’:
/home/daniel/srcs/libwebsockets/lib/tls/mbedtls/mbedtls-extensions.c:253:23: warning: implicit declaration of function ‘mbedtls_x509_get_name’; did you mean ‘mbedtls_pk_get_name’? [-Wimplicit-function-declaration]
  253 |                 ret = mbedtls_x509_get_name( p, end, &rfc822Name );
      |                       ^~~~~~~~~~~~~~~~~~~~~
      |                       mbedtls_pk_get_name
[ 31%] Building C object lib/CMakeFiles/websockets.dir/tls/tls-client.c.o
[ 31%] Building C object lib/CMakeFiles/websockets.dir/tls/mbedtls/mbedtls-client.c.o
[ 31%] Building C object lib/CMakeFiles/websockets_shared.dir/core/alloc.c.o
/home/daniel/srcs/libwebsockets/lib/tls/mbedtls/mbedtls-extensions.c: In function ‘lws_mbedtls_x509_parse_general_name’:
/home/daniel/srcs/libwebsockets/lib/tls/mbedtls/mbedtls-extensions.c:253:23: warning: implicit declaration of function ‘mbedtls_x509_get_name’; did you mean ‘mbedtls_pk_get_name’? [-Wimplicit-function-declaration]
  253 |                 ret = mbedtls_x509_get_name( p, end, &rfc822Name );
      |                       ^~~~~~~~~~~~~~~~~~~~~
      |                       mbedtls_pk_get_name
`
