### ISSUE TITLE
Make context->max_fds configurable to a lower number

### ISSUE THREAD

**Issue by vaind** [warmcat/libwebsockets#1578]
When using lws as a client-only, I'm getting unnecessarily high memory usage because of default settings of `ulimit -n` on some platforms (e.g. 1048576 on Manjaro).

I was able to partially fix the memory usage by lowering the `info.fd_limit_per_thread` but that only applies when allocating `context->pt[0].fds`. 

`context->max_fds` is used when allocating `context->lws_lookup` so being able to decrease it would save another ~10 megabytes of RAM.

While I understand using `rlimit` is a good default, could you please provide a configuration to decrease this? Alternatively, you could calculate the `max_fds` based on the number of threads and the `fd_limit_per_thread` - as you do in the other direction when that config is provided. That could be even better I guess as it doesn't introduce new configuration.

**Comment by lws-team** [comment]
The difficulty is that fds returned by socket() are stored in a map to make fd -> wsi lookups extremely cheap.  The fd returned by socket is an ordinal from 0 thru ulimit -n on *nix... so we create the map accordingly.

The quick solution is reduce ulimit -n.

**Comment by vaind** [comment]
Thanks for the quick reply. I see the problem... 

Reducing `ulimit -n` is what we're currently doing on our test setup but that's not something we can expect our users to do, especially when it's used as a library.

When is that lookup taking place? I've seen the code but it's not so obvious to me what are the actual situations when it's executed. Is it executed frequently in both client & server "modes"?

**Comment by greenrobot** [comment]
At least for clients it would be nice to limit this; how many fds does a client need?

**Comment by lws-team** [comment]
I agree, but there's no such restriction about beimg a client or a server in lws.  For example it offers h1 /h2 -> h1 and ws reverse proxying... it's equally a client and a server and there's no implication client should want less wsi.

I do see though that this optimization has come from a server pov and may not be an optimization any more for a minimal client on a box with big `ulimit -n`.

Let me take a look and I'll reply later.

**Comment by lws-team** [comment]
I pushed a patch on master which let's you use info.fd_limit_per_thread to control this... if it's left at the default zero, then all is as before.

However if you set it, and the amount multiplied by the number of service threads (usually 1) is less than ulimit -n, the fd table allocation is restricted accordingly and since we aren't able to map all possible fds any more, the map scheme is dynamically switched to using a linear search inside the restricted fd table.

If you are just using one or two clients, this means you can hold the fd table to 1 (internal cancel pipe) + 1 (your wsi) + 1 (if h2 is enabled, the network wsi for the your stream wsi), ie 3 pointers instead of ulimit -n.

The related minimal examples using just  one or a few clients are suitably adapted by the patch, eg

https://libwebsockets.org/git/libwebsockets/tree/minimal-examples/http-client/minimal-http-client/minimal-http-client.c#n133-140

At startup you can see the allocation amount for the fd table in bytes at INFO logging is now unrelated to ulimit -n on the changed examples, eg

```
[2019/05/18 13:53:30:2711] INFO:  mem: platform fd map:    24 B
```

Please give it a try.

**Comment by vaind** [comment]
Great to hear that, I'll give it a go and let you know. Thanks

**Comment by vaind** [comment]
current master doesn't compile with OpenSSL 1.1.1

```
lib/tls/openssl/openssl-client.c:428:3: error: implicit declaration of function 'EVP_MD_CTX_destroy' is invalid in C99 [-Werror,-Wimplicit-function-declaration]
                EVP_MD_CTX_destroy(mdctx);
                ^
```

I guess it should be using macro `EVP_MD_CTX_free`

**Comment by lws-team** [comment]
Can you delete your build/CMakeCache.txt and try again?

**Comment by vaind** [comment]
It has been a completely clean build (and I tried again anyway).

Here's a more complete log which seems to indicate the problem:
```
.../lws-48366de1d1a55f5b49ffd376133af0e272119b66-openssl/lib/tls/openssl/openssl-client.c:428:3: error: implicit declaration of function
      'EVP_MD_CTX_destroy' is invalid in C99 [-Werror,-Wimplicit-function-declaration]
                EVP_MD_CTX_destroy(mdctx);
                ^
.../openssl-1.1.1b/include/openssl/evp.h:539:34: note: expanded from macro 'EVP_MD_CTX_destroy'
# define EVP_MD_CTX_destroy(ctx) EVP_MD_CTX_free((ctx))
                                 ^
.../lws-48366de1d1a55f5b49ffd376133af0e272119b66-openssl/lib/tls/private.h:84:29: note: expanded from macro 'EVP_MD_CTX_free'
    #define EVP_MD_CTX_free EVP_MD_CTX_destroy
                            ^
```

OpenSSLs `evp.h` defines (I guess for backward compatibility)
```c
# define EVP_MD_CTX_destroy(ctx) EVP_MD_CTX_free((ctx))
```

and LWS `tls/private.h` defines
```c
#define EVP_MD_CTX_free EVP_MD_CTX_destroy
```

**Comment by vaind** [comment]
FYI: we've been using 3.1.0 release till now and it built & worked just fine.

**Comment by lws-team** [comment]
What exactly is your openssl version?

I create and buildtest lws on Fedora 30 with 1.1.1b, and there's no problem.

Lws also builds against openssl "3" development branch, at least of a couple of weeks ago.

**Comment by vaind** [comment]
We're building against OpenSSL 1.1.1b built with the following options:
```
        no-idea no-mdc2 no-rc5  
        no-ssl3
        no-shared
        no-psk
        no-srp
        no-comp
        no-zlib
        no-unit-test
        no-weak-ssl-ciphers
```

**Comment by lws-team** [comment]
It works fine with current up-to-date Fedora 30.

And... I clone current openssl and check out 1.1.1b and make it...

```
$ git clone https://github.com/openssl/openssl.git
$ cd openssl
$ git reset --hard OpenSSL_1_1_1b
HEAD is now at 50eaac9f33 Prepare for 1.1.1b release
$ ./config no-unit-test no-idea no-mdc2 no-rc5 no-ssl3 no-psk no-srp no-comp no-zlib no-weak-ssl-ciphers
$ make -j 8
...
```

then to build lws against that

```
$ cd /projects/libwebsockets
$ mkdir bb
$ cd bb
$ cmake .. -DLWS_WITH_HTTP2=1 -DLWS_OPENSSL_INCLUDE_DIRS=/projects/openssl/include -DLWS_OPENSSL_LIBRARIES="/projects/openssl/libssl.so;/projects/openssl/libcrypto.so"
$ make -j8
```

Builds fine.  I confirmed it's taking the correct headers by temporarily adding a string xxx to the top of /projects/openssl/include/openssl/ssl.h and watch lws fail to build on it.

```
$ gcc -v
Using built-in specs.
COLLECT_GCC=/usr/bin/gcc
COLLECT_LTO_WRAPPER=/usr/libexec/gcc/x86_64-redhat-linux/9/lto-wrapper
OFFLOAD_TARGET_NAMES=nvptx-none
OFFLOAD_TARGET_DEFAULT=1
Target: x86_64-redhat-linux
Configured with: ../configure --enable-bootstrap --enable-languages=c,c++,fortran,objc,obj-c++,ada,go,d,lto --prefix=/usr --mandir=/usr/share/man --infodir=/usr/share/info --with-bugurl=http://bugzilla.redhat.com/bugzilla --enable-shared --enable-threads=posix --enable-checking=release --enable-multilib --with-system-zlib --enable-__cxa_atexit --disable-libunwind-exceptions --enable-gnu-unique-object --enable-linker-build-id --with-gcc-major-version-only --with-linker-hash-style=gnu --enable-plugin --enable-initfini-array --with-isl --enable-offload-targets=nvptx-none --without-cuda-driver --enable-gnu-indirect-function --enable-cet --with-tune=generic --with-arch_32=i686 --build=x86_64-redhat-linux
Thread model: posix
gcc version 9.1.1 20190503 (Red Hat 9.1.1-1) (GCC) 
```

...
