### ISSUE TITLE
Compiling master branch with plugins support fails with -Werror=format-security

### ISSUE THREAD

**Issue by hkozachkov** [warmcat/libwebsockets#624]
Compiling with plugins enabled in the master branch fails with -Werror=format-security:

 libwebsockets/plugins/generic-table/protocol_table_dirlisting.c:155:3: error: format not a string literal and no format arguments [-Werror=format-security]
   n = snprintf(pss->p, end - pss->p, icon);

release version v2.0.1 compiles with no issues.

git blame reports that this issue was introduced with commit 722cc4a3

722cc4a3 (Andy Green 2016-06-26 06:29:20 +0800 155)

I'm using gcc 5.4.1 on ubuntu 16.04

Sorry if this issue is already documented somewhere .. I didn't notice.

**Comment by lws-team** [comment]
I pushed a patch adding the format string, but this is a false alarm by the compiler.  The `icon` pointer may only point to " " or "&#x1f4c2;", nothing else.

The warning doesn't appear on Fedora's gcc 6.1.1 or whatever Travis and Appveyor use either  But anyway... it's gone now.
