### ISSUE TITLE
Windows build problem in version 4.3.3

### ISSUE THREAD

**Issue by slavomir-predajnos** [warmcat/libwebsockets#3020]
Windows build v4.3.3 ends with an error:

LINK: command "C:\PROGRA~1\MIB055~1\2022\PROFES~1\VC\Tools\MSVC\1434~1.319\bin\Hostx64\x64\link.exe /nologo @CMakeFiles\websockets_shared.dir\objects1.rsp /out:..\bin\websockets.dll /implib:websockets.lib /pdb:C:\Data\libwebsockets\build\bin\websockets.pdb /dll /version:0.0 /machine:x64 /INCREMENTAL:NO C:\Program Files\OpenSSL-Win64\lib\libssl.lib C:\Program Files\OpenSSL-Win64\lib\libcrypto.lib ws2_32.lib userenv.lib psapi.lib iphlpapi.lib crypt32.lib kernel32.lib user32.lib gdi32.lib winspool.lib shell32.lib ole32.lib oleaut32.lib uuid.lib comdlg32.lib advapi32.lib /MANIFEST /MANIFESTFILE:..\bin\websockets.dll.manifest" failed (exit code 1120) with the following output:
   Creating library websockets.lib and object websockets.exp
extension-permessage-deflate.c.obj : error LNK2019: unresolved external symbol deflate referenced in function lws_extension_callback_pm_deflate
extension-permessage-deflate.c.obj : error LNK2019: unresolved external symbol deflateEnd referenced in function lws_extension_callback_pm_deflate
extension-permessage-deflate.c.obj : error LNK2019: unresolved external symbol inflate referenced in function lws_extension_callback_pm_deflate
extension-permessage-deflate.c.obj : error LNK2019: unresolved external symbol inflateEnd referenced in function lws_extension_callback_pm_deflate
extension-permessage-deflate.c.obj : error LNK2019: unresolved external symbol deflatePending referenced in function lws_extension_callback_pm_deflate
extension-permessage-deflate.c.obj : error LNK2019: unresolved external symbol deflateInit2_ referenced in function lws_extension_callback_pm_deflate
extension-permessage-deflate.c.obj : error LNK2019: unresolved external symbol inflateInit2_ referenced in function lws_extension_callback_pm_deflate
..\bin\websockets.dll : fatal error LNK1120: 7 unresolved externals

The same result is when using openssl in both 1.1.1w and 3.1.4.

On the older version v4.3.2, the build with openssl v1.1.1w is successful, but the build with openssl 3.1.4 ends with an error:
openssl-server.c
C:\Data\libwebsockets\lib\tls\openssl\openssl-server.c(436): error C2220: the following warning is treated as an error
C:\Data\libwebsockets\lib\tls\openssl\openssl-server.c(436): warning C4996: 'EC_KEY_new_by_curve_name': Since OpenSSL 3.0
C:\Data\libwebsockets\lib\tls\openssl\openssl-server.c(442): warning C4996: 'EC_KEY_free': Since OpenSSL 3.0
C:\Data\libwebsockets\lib\tls\openssl\openssl-server.c(485): warning C4996: 'EVP_PKEY_get1_EC_KEY': Since OpenSSL 3.0
C:\Data\libwebsockets\lib\tls\openssl\openssl-server.c(493): warning C4996: 'EC_KEY_free': Since OpenSSL 3.0
NMAKE : fatal error U1077: '"C:\Program Files\Microsoft Visual Studio\2022\Professional\Common7\IDE\CommonExtensions\Microsoft\CMake\CMake\bin\cmake.exe"' : return code '0x2'
Stop.
NMAKE : fatal error U1077: '"C:\Program Files\Microsoft Visual Studio\2022\Professional\VC\Tools\MSVC\14.34.31933\bin\HostX64\x64\nmake.exe"' : return code '0x2'
Stop.
NMAKE : fatal error U1077: '"C:\Program Files\Microsoft Visual Studio\2022\Professional\VC\Tools\MSVC\14.34.31933\bin\HostX64\x64\nmake.exe"' : return code '0x2'
Stop.

Can you advise me how to successfully build libwebsocket together with openssl 3.1.4?

**Comment by zzblydia** [comment]
"error LNK2019: unresolved external symbol deflate referenced" means you may miss zlib library dependency in env.
warning C4996 means Deprecated function, you can suppress this specific warning in Visual Studio for building successfully.

**Comment by slavomir-predajnos** [comment]
Build for the older version v4.3.2 with openssl 1.1.1w was successful, so it probably won't be the missing zlib in env

**Comment by lws-team** [comment]
The first set of errors you mentioned do look like failing to link against zlib.

The second set look like they should have been zapped with `LWS_SUPPRESS_DEPRECATED_API_WARNINGS` being set by default, maybe something else needed for that on windows.  Also as zzblydia suggested, you can maybe manually turn off deprecated warnings on msvc.

**Comment by slavomir-predajnos** [comment]
The build is successful if I add LWS_WITH_BUNDLED_ZLIB=OFF. Thanks for advice.
