### ISSUE TITLE
Single command installation of libwebsockets

### ISSUE THREAD

**Issue by sacOO7** [warmcat/libwebsockets#1287]
Hi there, thank you for developing such an amazing websocket library. I am currently using this one in https://github.com/sacOO7/socketcluster-client-C. The only problem is managing the dependency of libwebsockets. It is little difficult to install it on different platforms. Will it be possible for you guys to write a single script which will solve this problem ( Execute once and it will build whole libwebsockets on the target platform). Please let me know your thoughts on this. Thank you once again !!!!

**Comment by lws-team** [comment]
> The only problem is managing the dependency of libwebsockets. It is little difficult to install it on different platforms. 

What does it actually mean?  Which "different platforms" make trouble with lws?

>  Will it be possible for you guys to write a single script which will solve this problem

I don't understand what the problem is yet.

**Comment by sacOO7** [comment]
Well I had faced lot of issues while installing this library in ubuntu 14.04. Most of them were compilation errors and additional dependencies while building the lws. You can check them here
https://github.com/warmcat/libwebsockets/issues/742
Actually just building the library took lot of time for me ( almost 2 days)  and also going through the required documentation ( Most of the websocket clients are event driven and only important aspects of library are presented). Like this one https://github.com/sacOO7/GoWebsocket. It might be because I am not that good with cmake. But I think it is supposed to be pretty easy.

**Comment by lws-team** [comment]
> Well I had faced lot of issues while installing this library in ubuntu 14.04

Uhhhhh every commit of lws builds in travis in trusty / 14.04.  For years now.

https://travis-ci.org/warmcat/libwebsockets/builds
