### ISSUE TITLE
4.4.1 fails to build on OpenBSD 7.8: wol.c ETHER_ADDR_LEN define location

### ISSUE THREAD

**Issue by pwrdwnsys** [warmcat/libwebsockets#3471]
Commit 457f860 references define location of ETHER_ADDR_LEN for NetBSD in `net/if_ether.h`. OpenBSD uses `netinet/if_ether.h` which in turn depends on definitions in `net/if_arp.h`, causing the cmake compile test that sets `LWS_HAVE_NET_IF_ETHER_H` to fail, but if succeeded would not find the correct defines.

```sh
[ 33%] Building C object lib/CMakeFiles/websockets.dir/core-net/wol.c.o
/home/pwrdwnsys/code/libwebsockets/lib/core-net/wol.c:31:26: error: use of undeclared identifier 'ETHER_ADDR_LEN'
   31 |         uint8_t pkt[17 * LWS_ETHER_ADDR_LEN];
      |                          ^
/home/pwrdwnsys/code/libwebsockets/include/libwebsockets.h:60:28: note: expanded from macro 'LWS_ETHER_ADDR_LEN'
   60 | #define LWS_ETHER_ADDR_LEN ETHER_ADDR_LEN
      |                            ^
/home/pwrdwnsys/code/libwebsockets/lib/core-net/wol.c:63:25: error: use of undeclared identifier 'ETHER_ADDR_LEN'
   63 |         for (n = 0; n < ETHER_ADDR_LEN; n++)
      |                         ^
/home/pwrdwnsys/code/libwebsockets/lib/core-net/wol.c:66:33: error: use of undeclared identifier 'ETHER_ADDR_LEN'
   66 |                 for (n = 0; n < ETHER_ADDR_LEN; n++)
      |                                 ^
3 errors generated.
*** Error 1 in . (lib/CMakeFiles/websockets.dir/build.make:1129 'lib/CMakeFiles/websockets.dir/core-net/wol.c.o': cd /home/pwrdwnsys/code/libwebs...)
*** Error 2 in . (CMakeFiles/Makefile2:1615 'lib/CMakeFiles/websockets.dir/all': make -s -f lib/CMakeFiles/websockets.dir/build.make lib/CMa...)
*** Error 2 in /home/pwrdwnsys/code/libwebsockets/build (Makefile:166 'all': make -s -f CMakeFiles/Makefile2 all)
```

**Comment by pwrdwnsys** [comment]
```git
--- a/include/libwebsockets.h
+++ b/include/libwebsockets.h
@@ -168,6 +168,12 @@ typedef int suseconds_t;
 #include <netinet/in.h>
 #endif

+/* Find ETHER_ADDR_LEN on OpenBSD */
+#if defined(__OpenBSD__)
+#include <net/if_arp.h>
+#include <netinet/if_ether.h>
+#endif
+
 #define LWS_INLINE inline
 #define LWS_O_RDONLY O_RDONLY
 #define LWS_O_WRONLY O_WRONLY
```
This patch seems to fix the build issue
