### ISSUE TITLE
LWS fails to build on windows with openssl 1.1.1d in vcpkg due to missing symbols

### ISSUE THREAD

**Issue by Neumann-A** [warmcat/libwebsockets#1715]
Reason: 

All checks fail due to the following error:
```
libcrypto.lib(e_capi.obj) : error LNK2019: unresolved external symbol __imp_CertOpenStore referenced in function capi_open_store

libcrypto.lib(e_capi.obj) : error LNK2019: unresolved external symbol __imp_CertCloseStore referenced in function capi_find_key

libcrypto.lib(e_capi.obj) : error LNK2019: unresolved external symbol __imp_CertEnumCertificatesInStore referenced in function capi_find_cert

libcrypto.lib(e_capi.obj) : error LNK2019: unresolved external symbol __imp_CertFindCertificateInStore referenced in function capi_find_cert

libcrypto.lib(e_capi.obj) : error LNK2019: unresolved external symbol __imp_CertDuplicateCertificateContext referenced in function capi_load_ssl_client_cert

libcrypto.lib(e_capi.obj) : error LNK2019: unresolved external symbol __imp_CertFreeCertificateContext referenced in function capi_dsa_free

libcrypto.lib(e_capi.obj) : error LNK2019: unresolved external symbol __imp_CertGetCertificateContextProperty referenced in function capi_cert_get_fname
```

Solution:
CMake must be told to also link `crypt32.lib` in the checks!

**Comment by lws-team** [comment]
Okay... can you send a patch or paste a diff pleaee?

**Comment by Neumann-A** [comment]
```
diff --git a/CMakeLists.txt b/CMakeLists.txt
index 4daeec85e..34e5e197d 100644
--- a/CMakeLists.txt	
+++ b/CMakeLists.txt
@@ -1822,7 +1822,7 @@ endif()
 if (WINCE)
 	list(APPEND LIB_LIST ws2.lib)
 elseif (WIN32)
-	list(APPEND LIB_LIST ws2_32.lib userenv.lib psapi.lib iphlpapi.lib)
+	list(APPEND LIB_LIST ws2_32.lib userenv.lib psapi.lib iphlpapi.lib crypt32.lib)
 endif()
 
 if (${CMAKE_SYSTEM_NAME} MATCHES "QNX")

```

this also includes crypt32 in the generated targets. Don't know if it is the universal correct location for that change (since your CMakeLists.txt is way too long) but with that change it compiles fine.

**Comment by lws-team** [comment]
> list(APPEND LIB_LIST ws2_32.lib userenv.lib psapi.lib iphlpapi.lib crypt32.lib)

I don't understand why this is suddenly needed, this has been linking ok for windows + openssl for a long time.  Until now libcrypto didn't use CAPI?

> since your CMakeLists.txt is way too long

It supports a lot of things you don't care about.  If you think you can make it shorter while supporting all the use-cases and platforms, knock yourself out.  If you can't... well, it's the right size for what it does then, isn't it.

**Comment by Neumann-A** [comment]
>I don't understand why this is suddenly needed, this has been linking ok for windows + openssl for a long time. Until now libcrypto didn't use CAPI?

Probably because I am building x64-windows-static. In the dynamic case it will never matter.  
But here is and openssl issue about it: https://github.com/openssl/openssl/issues/1061

> It supports a lot of things you don't care about. If you think you can make it shorter while supporting all the use-cases and platforms, knock yourself out. If you can't... well, it's the right size for what it does then, isn't it.

wrong assumption. I care about all of it but i also care about the representation :). For example you have a lot of options. Maybe `include(LWSBuildOptions.cmake)` instead of having them all in the main CMakeLists.txt. The same goes for the check function exist part. Simply including a well named file would make reading and understanding the CMakeLists.txt so much easier.

**Comment by lws-team** [comment]
>  I care about all of it but i also care about the representation :).

Wonderful... send (tested) patches :-)

**Comment by lws-team** [comment]
> In the dynamic case it will never matter.

It'd be great if the patch for the cmake part adding the dep on this other library was dependent on the build being static as well then.

**Comment by Neumann-A** [comment]
> It'd be great if the patch for the cmake part adding the dep on this other library was dependent on the build being static as well then.

will not work since you need to know if OpenSSL has been build as a static library and not libwebsockets.

**Comment by WenchaoXia** [comment]
with openssl 1.1.1 x64 win10 building fails since "struct ssl_ctx_st" is not defined in public header files but in 1.02 it is.

**Comment by WenchaoXia** [comment]
I am linking it with UE4's prebuilt openssl 1.1.1 static lib, is there a way to make websocketstatic.lib compatiable with openssl 1.1.1 static lib?

**Comment by lws-team** [comment]
> building fails since "struct ssl_ctx_st" is not defined in public header files

I can build against 1.1.1d just fine here on Linux.

All of our uses of SSL_CTX are via a pointer, we don't actually need any definition of struct ssl_ctx_st.

Can you paste your actual compile error?

**Comment by WenchaoXia** [comment]
F:\UE4\Projects\ext\libwebsockets\lib\tls\openssl\openssl-server.c(422): error C2037: left of 'extra_certs' specifies undefined struct/union 'ssl_ctx_st'

#if !defined(LWS_HAVE_SSL_EXTRA_CHAIN_CERTS)
	x = sk_X509_value(vhost->tls.ssl_ctx->extra_certs, 0);
#else

maybe use LWS_HAVE_SSL_EXTRA_CHAIN_CERTS can bypass this problem?

**Comment by lws-team** [comment]
Because there are so many api variations in openssl versions, lws takes the approach to get cmake to check if specific apis exist on the version of the lib you have on your actual platform... it's hopeless trying to figure it out by openssl version.

https://libwebsockets.org/git/libwebsockets/tree/CMakeLists.txt?h=master#n1982

It basically builds a little test app for each one and sees what happens... if it builds, then it sets the corresponding flag define to let lws know it's OK to use it.  In this way it can work out a way to build using the latest bits your openssl lib has available.

For whatever reason (the OP's problem on this issue?) your cmake didn't set this flag... you can go look in `build/CMakeFiles/CMakeError.log` and search for eg, 'SSL_CTX_get_extra_chain_certs_only' to find out what went wrong... if it's related to OP's problem, try OP's patch.

**Comment by WenchaoXia** [comment]
I found the reason, the cmake did not set the flag since the compile test fail while trying to use system installed ssl header file, while I manually set it by -DLWS_OPENSSL_INCLUDE_DIRS:PATH=G:\UE4\src\UE4\Engine\Source\ThirdParty\OpenSSL\1.1.1\Include\Win64\VS2015.

Allow me to ask another stupid question:
how to tell libwebsockets cmake, link more than one library?
I used
-DLWS_OPENSSL_LIBRARIES:PATH="G:\UE4\src\UE4\Engine\Source\ThirdParty\OpenSSL\1.1.1\Lib\Win64\VS2015\Release\libssl.lib,G:\UE4\src\UE4\Engine\Source\ThirdParty\OpenSSL\1.1.1\Lib\Win64\VS2015\Release\libcrypto.lib"
but compile fail, how do I tell the script linking both libssl.lib and libcrypto.lib?

**Comment by lws-team** [comment]
The big secret is separate with ;

Although cmake can be a bit mysterious it is actually really effective especially on cross build.

**Comment by lws-team** [comment]
I take it this worked and solves the original problem without the patch.

**Comment by Neumann-A** [comment]
@lws-team: Closed for the wrong reasons .... original issue was on windows closed because of a different issue/solution on linux? If you did not commit any change to the cmakelists.txt regarding the crypt32 linkage on windows if openssl has been built statically the issue is simply not resolved and should not be closed......

**Comment by lws-team** [comment]
It seems WenchaoXia's problem is the same, and it's on windows... and he solved it without needing a patch... so...

**Comment by Neumann-A** [comment]
@lws-team: A yeah right about the platform. seems like I mixed it up with another issue. Still linking against crypt32 is required and must be done by CMake. Just google "openssl crypt32" and you will find enough issues that this is required.  There is also a CMake issue about it https://gitlab.kitware.com/cmake/cmake/issues/19263

**Comment by samuel-tranchet** [comment]
> 
> 
> ```
> diff --git a/CMakeLists.txt b/CMakeLists.txt
> index 4daeec85e..34e5e197d 100644
> --- a/CMakeLists.txt	
> +++ b/CMakeLists.txt
> @@ -1822,7 +1822,7 @@ endif()
>  if (WINCE)
>  	list(APPEND LIB_LIST ws2.lib)
>  elseif (WIN32)
> -	list(APPEND LIB_LIST ws2_32.lib userenv.lib psapi.lib iphlpapi.lib)
> +	list(APPEND LIB_LIST ws2_32.lib userenv.lib psapi.lib iphlpapi.lib crypt32.lib)
>  endif()
>  
>  if (${CMAKE_SYSTEM_NAME} MATCHES "QNX")
> ```
> 
> this also includes crypt32 in the generated targets. Don't know if it is the universal correct location for that change (since your CMakeLists.txt is way too long) but with that change it compiles fine.

This patch is definitely needed, static LWS 4.0 won't compile without it on Windows with latest static OpenSSL 1.1.1

**Comment by lws-team** [comment]
Lws has been building fine on windows without that in CI, using a locally-built default openssl... it may be needed on very latest openssl or it may be needed if some options selected in openssl (perhaps integration to OS trust store).  I think that's a windows lib anyway so it shouldn't make trouble to just add it... I pushed a patch on v4.0-stable and there's a matching patch on master later.
