### ISSUE TITLE
test-client doesn't build on OS X

### ISSUE THREAD

**Issue by bprodoehl** [warmcat/libwebsockets#395]
Thanks for the great library! Trying to build on OS X with LLVM version 7.0.2, test-client.c fails with these errors:

```
[ 35%] Building C object CMakeFiles/test-client.dir/test-server/test-client.c.o
/Users/me/src/libwebsockets/test-server/test-client.c:175:11: error: taking the absolute value of unsigned type 'unsigned int' has no effect [-Werror,-Wabsolute-value]
                                        (int)abs(rands[1] % 500),
                                             ^
/usr/include/secure/_stdio.h:47:56: note: expanded from macro 'sprintf'
  __builtin___sprintf_chk (str, 0, __darwin_obsz(str), __VA_ARGS__)
                                                       ^
/Users/me/src/libwebsockets/test-server/test-client.c:175:11: note: remove the call to 'abs' since unsigned values cannot be negative
                                        (int)abs(rands[1] % 500),
                                             ^~~
/usr/include/secure/_stdio.h:47:56: note: expanded from macro 'sprintf'
  __builtin___sprintf_chk (str, 0, __darwin_obsz(str), __VA_ARGS__)
                                                       ^
/Users/me/src/libwebsockets/test-server/test-client.c:176:11: error: taking the absolute value of unsigned type 'unsigned int' has no effect [-Werror,-Wabsolute-value]
                                        (int)abs(rands[2] % 250),
                                             ^
/usr/include/secure/_stdio.h:47:56: note: expanded from macro 'sprintf'
  __builtin___sprintf_chk (str, 0, __darwin_obsz(str), __VA_ARGS__)
                                                       ^
/Users/me/src/libwebsockets/test-server/test-client.c:176:11: note: remove the call to 'abs' since unsigned values cannot be negative
                                        (int)abs(rands[2] % 250),
                                             ^~~
/usr/include/secure/_stdio.h:47:56: note: expanded from macro 'sprintf'
  __builtin___sprintf_chk (str, 0, __darwin_obsz(str), __VA_ARGS__)
                                                       ^
/Users/me/src/libwebsockets/test-server/test-client.c:177:11: error: taking the absolute value of unsigned type 'unsigned int' has no effect [-Werror,-Wabsolute-value]
                                        (int)abs(rands[3] % 24));
                                             ^
/usr/include/secure/_stdio.h:47:56: note: expanded from macro 'sprintf'
  __builtin___sprintf_chk (str, 0, __darwin_obsz(str), __VA_ARGS__)
                                                       ^
/Users/me/src/libwebsockets/test-server/test-client.c:177:11: note: remove the call to 'abs' since unsigned values cannot be negative
                                        (int)abs(rands[3] % 24));
                                             ^~~
/usr/include/secure/_stdio.h:47:56: note: expanded from macro 'sprintf'
  __builtin___sprintf_chk (str, 0, __darwin_obsz(str), __VA_ARGS__)
                                                       ^
3 errors generated.
```

**Comment by lws-team** [comment]
Well, it does "build on OSX" according to Travis.

https://travis-ci.org/warmcat/libwebsockets

I added the abs() because I noticed in the javascript console for the test client he was complaining about being asked to draw a circle with a negative radius (gcc 5.3 on Linux).  That went away with abs.

Googling for evidence to back that up though, % operator before C99 had some implementation-defined behaviours and reading what there is about it, I'm not sure gcc's action is defensible actually.  Although having observed it and made it go away, I am certain that's what it is doing.

I solved it by just using bitwise & and converting to %u in the sprintf.
