### ISSUE TITLE
Build doesn't work on Ubuntu 20.20

### ISSUE THREAD

**Issue by georgii-ivanov** [warmcat/libwebsockets#2003]
No CMake flags, CMake successful

CMake Output:
```
-- Compiled with LWS_WITH_DIR and LWS_WITH_LEJP_CONF
Git commit hash: v4.0.0-274-gdd3bae8c
Compiling with SSL support
OpenSSL include dir: /usr/include
OpenSSL libraries: /usr/lib/x86_64-linux-gnu/libssl.so;/usr/lib/x86_64-linux-gnu/libcrypto.so;ssl;crypto
Searching for OpenSSL executable and dlls
OpenSSL executable: /usr/bin/openssl
 GENCERTS = 1
Generating SSL Certificates for the test-server...
Generating a RSA private key
......+++++
................................+++++
writing new private key to '/home/appstack/libwebsockets/build/libwebsockets-test-server.key.pem'
-----
You are about to be asked to enter information that will be incorporated
into your certificate request.
What you are about to enter is what is called a Distinguished Name or a DN.
There are quite a few fields but you can leave some blank
For some fields there will be a default value,
If you enter '.', the field will be left blank.
-----
Country Name (2 letter code) [AU]:State or Province Name (full name) [Some-State]:Locality Name (eg, city) []:Organization Name (eg, company) [Internet Widgits Pty Ltd]:Organizational Unit Name (eg, section) []:Common Name (e.g. server FQDN or YOUR name) []:Email Address []:SUCCESSFULLY generated SSL certificate
DIR /home/appstack/libwebsockets/build CMP /home/appstack/libwebsockets/cmake
-- Configuring done
-- Generating done
-- Build files have been written to: /home/appstack/libwebsockets/build
```

Errors on make:

```
[  1%] Building C object lib/CMakeFiles/websockets_shared.dir/misc/dir.c.o
/home/appstack/libwebsockets/lib/misc/dir.c:152:5: error: 'DT_BLK' is not defined, evaluates to 0 [-Werror,-Wundef]
#if DT_BLK != DT_UNKNOWN
    ^
/usr/include/dirent.h:108:18: note: expanded from macro 'DT_BLK'
# define DT_BLK         DT_BLK
                        ^
/home/appstack/libwebsockets/lib/misc/dir.c:152:15: error: 'DT_UNKNOWN' is not defined, evaluates to 0 [-Werror,-Wundef]
#if DT_BLK != DT_UNKNOWN
              ^
/usr/include/dirent.h:100:21: note: expanded from macro 'DT_UNKNOWN'
# define DT_UNKNOWN     DT_UNKNOWN
                        ^
/home/appstack/libwebsockets/lib/misc/dir.c:157:5: error: 'DT_CHR' is not defined, evaluates to 0 [-Werror,-Wundef]
#if DT_CHR != DT_UNKNOWN
    ^
/usr/include/dirent.h:104:18: note: expanded from macro 'DT_CHR'
# define DT_CHR         DT_CHR
                        ^
/home/appstack/libwebsockets/lib/misc/dir.c:157:15: error: 'DT_UNKNOWN' is not defined, evaluates to 0 [-Werror,-Wundef]
#if DT_CHR != DT_UNKNOWN
              ^
/usr/include/dirent.h:100:21: note: expanded from macro 'DT_UNKNOWN'
# define DT_UNKNOWN     DT_UNKNOWN
                        ^
/home/appstack/libwebsockets/lib/misc/dir.c:162:5: error: 'DT_DIR' is not defined, evaluates to 0 [-Werror,-Wundef]
#if DT_DIR != DT_UNKNOWN
    ^
/usr/include/dirent.h:106:18: note: expanded from macro 'DT_DIR'
# define DT_DIR         DT_DIR
                        ^
/home/appstack/libwebsockets/lib/misc/dir.c:162:15: error: 'DT_UNKNOWN' is not defined, evaluates to 0 [-Werror,-Wundef]
#if DT_DIR != DT_UNKNOWN
              ^
/usr/include/dirent.h:100:21: note: expanded from macro 'DT_UNKNOWN'
# define DT_UNKNOWN     DT_UNKNOWN
                        ^
/home/appstack/libwebsockets/lib/misc/dir.c:167:5: error: 'DT_FIFO' is not defined, evaluates to 0 [-Werror,-Wundef]
#if DT_FIFO != DT_UNKNOWN
    ^
/usr/include/dirent.h:102:18: note: expanded from macro 'DT_FIFO'
# define DT_FIFO        DT_FIFO
                        ^
/home/appstack/libwebsockets/lib/misc/dir.c:167:16: error: 'DT_UNKNOWN' is not defined, evaluates to 0 [-Werror,-Wundef]
#if DT_FIFO != DT_UNKNOWN
               ^
/usr/include/dirent.h:100:21: note: expanded from macro 'DT_UNKNOWN'
# define DT_UNKNOWN     DT_UNKNOWN
                        ^
/home/appstack/libwebsockets/lib/misc/dir.c:172:5: error: 'DT_LNK' is not defined, evaluates to 0 [-Werror,-Wundef]
#if DT_LNK != DT_UNKNOWN
    ^
/usr/include/dirent.h:112:18: note: expanded from macro 'DT_LNK'
# define DT_LNK         DT_LNK
                        ^
/home/appstack/libwebsockets/lib/misc/dir.c:172:15: error: 'DT_UNKNOWN' is not defined, evaluates to 0 [-Werror,-Wundef]
#if DT_LNK != DT_UNKNOWN
              ^
/usr/include/dirent.h:100:21: note: expanded from macro 'DT_UNKNOWN'
# define DT_UNKNOWN     DT_UNKNOWN
                        ^
/home/appstack/libwebsockets/lib/misc/dir.c:180:5: error: 'DT_SOCK' is not defined, evaluates to 0 [-Werror,-Wundef]
#if DT_SOCK != DT_UNKNOWN
    ^
/usr/include/dirent.h:114:18: note: expanded from macro 'DT_SOCK'
# define DT_SOCK        DT_SOCK
                        ^
/home/appstack/libwebsockets/lib/misc/dir.c:180:16: error: 'DT_UNKNOWN' is not defined, evaluates to 0 [-Werror,-Wundef]
#if DT_SOCK != DT_UNKNOWN
               ^
/usr/include/dirent.h:100:21: note: expanded from macro 'DT_UNKNOWN'
# define DT_UNKNOWN     DT_UNKNOWN
```

**Comment by lws-team** [comment]
Sorry what exact ubuntu version?  There's no problem on 20.04 + default cmake options

https://libwebsockets.org/sai/index.html?task=b2410c8bbfd30d86fcc0886f0b687c556f76d5d80a0c6d01f66ee8fe2a188ecc

**Comment by georgii-ivanov** [comment]
Sorry. Ubuntu 20.04, right.
But do you have any idea what it could be related to?

**Comment by georgii-ivanov** [comment]
Make command build log:

```
appstack@9CF4CF8:~/libwebsockets/build$ make
Scanning dependencies of target GENHDR
[  0%] Creating build include dir
[  0%] Built target GENHDR
Scanning dependencies of target websockets_shared
[  0%] Building C object lib/CMakeFiles/websockets_shared.dir/plat/unix/unix-caps.c.o
[  1%] Building C object lib/CMakeFiles/websockets_shared.dir/plat/unix/unix-misc.c.o
[  2%] Building C object lib/CMakeFiles/websockets_shared.dir/plat/unix/unix-init.c.o
[  2%] Building C object lib/CMakeFiles/websockets_shared.dir/plat/unix/unix-file.c.o
[  3%] Building C object lib/CMakeFiles/websockets_shared.dir/plat/unix/unix-pipe.c.o
[  4%] Building C object lib/CMakeFiles/websockets_shared.dir/plat/unix/unix-service.c.o
[  4%] Building C object lib/CMakeFiles/websockets_shared.dir/plat/unix/unix-sockets.c.o
[  5%] Building C object lib/CMakeFiles/websockets_shared.dir/plat/unix/unix-fds.c.o
[  6%] Building C object lib/CMakeFiles/websockets_shared.dir/tls/tls.c.o
[  6%] Building C object lib/CMakeFiles/websockets_shared.dir/tls/tls-network.c.o
[  7%] Building C object lib/CMakeFiles/websockets_shared.dir/tls/openssl/openssl-tls.c.o
[  8%] Building C object lib/CMakeFiles/websockets_shared.dir/tls/openssl/openssl-x509.c.o
[  8%] Building C object lib/CMakeFiles/websockets_shared.dir/tls/openssl/openssl-ssl.c.o
[  9%] Building C object lib/CMakeFiles/websockets_shared.dir/tls/tls-server.c.o
[ 10%] Building C object lib/CMakeFiles/websockets_shared.dir/tls/openssl/openssl-server.c.o
[ 10%] Building C object lib/CMakeFiles/websockets_shared.dir/tls/tls-client.c.o
[ 11%] Building C object lib/CMakeFiles/websockets_shared.dir/tls/openssl/openssl-client.c.o
[ 12%] Building C object lib/CMakeFiles/websockets_shared.dir/core/alloc.c.o
[ 12%] Building C object lib/CMakeFiles/websockets_shared.dir/core/buflist.c.o
[ 13%] Building C object lib/CMakeFiles/websockets_shared.dir/core/context.c.o
[ 14%] Building C object lib/CMakeFiles/websockets_shared.dir/core/lws_dll2.c.o
[ 14%] Building C object lib/CMakeFiles/websockets_shared.dir/core/libwebsockets.c.o
[ 15%] Building C object lib/CMakeFiles/websockets_shared.dir/core/logs.c.o
[ 16%] Building C object lib/CMakeFiles/websockets_shared.dir/core/vfs.c.o
[ 16%] Building C object lib/CMakeFiles/websockets_shared.dir/misc/base64-decode.c.o
[ 17%] Building C object lib/CMakeFiles/websockets_shared.dir/misc/lws-ring.c.o
[ 18%] Building C object lib/CMakeFiles/websockets_shared.dir/misc/dir.c.o
/home/appstack/libwebsockets/lib/misc/dir.c:152:5: error: 'DT_BLK' is not defined, evaluates to 0 [-Werror,-Wundef]
#if DT_BLK != DT_UNKNOWN
    ^
/usr/include/dirent.h:108:18: note: expanded from macro 'DT_BLK'
# define DT_BLK         DT_BLK
                        ^
/home/appstack/libwebsockets/lib/misc/dir.c:152:15: error: 'DT_UNKNOWN' is not defined, evaluates to 0 [-Werror,-Wundef]
#if DT_BLK != DT_UNKNOWN
              ^
/usr/include/dirent.h:100:21: note: expanded from macro 'DT_UNKNOWN'
# define DT_UNKNOWN     DT_UNKNOWN
                        ^
/home/appstack/libwebsockets/lib/misc/dir.c:157:5: error: 'DT_CHR' is not defined, evaluates to 0 [-Werror,-Wundef]
#if DT_CHR != DT_UNKNOWN
    ^
/usr/include/dirent.h:104:18: note: expanded from macro 'DT_CHR'
# define DT_CHR         DT_CHR
                        ^
/home/appstack/libwebsockets/lib/misc/dir.c:157:15: error: 'DT_UNKNOWN' is not defined, evaluates to 0 [-Werror,-Wundef]
#if DT_CHR != DT_UNKNOWN
              ^
/usr/include/dirent.h:100:21: note: expanded from macro 'DT_UNKNOWN'
# define DT_UNKNOWN     DT_UNKNOWN
                        ^
/home/appstack/libwebsockets/lib/misc/dir.c:162:5: error: 'DT_DIR' is not defined, evaluates to 0 [-Werror,-Wundef]
#if DT_DIR != DT_UNKNOWN
    ^
/usr/include/dirent.h:106:18: note: expanded from macro 'DT_DIR'
# define DT_DIR         DT_DIR
                        ^
/home/appstack/libwebsockets/lib/misc/dir.c:162:15: error: 'DT_UNKNOWN' is not defined, evaluates to 0 [-Werror,-Wundef]
#if DT_DIR != DT_UNKNOWN
              ^
/usr/include/dirent.h:100:21: note: expanded from macro 'DT_UNKNOWN'
# define DT_UNKNOWN     DT_UNKNOWN
                        ^
/home/appstack/libwebsockets/lib/misc/dir.c:167:5: error: 'DT_FIFO' is not defined, evaluates to 0 [-Werror,-Wundef]
#if DT_FIFO != DT_UNKNOWN
    ^
/usr/include/dirent.h:102:18: note: expanded from macro 'DT_FIFO'
# define DT_FIFO        DT_FIFO
                        ^
/home/appstack/libwebsockets/lib/misc/dir.c:167:16: error: 'DT_UNKNOWN' is not defined, evaluates to 0 [-Werror,-Wundef]
#if DT_FIFO != DT_UNKNOWN
               ^
/usr/include/dirent.h:100:21: note: expanded from macro 'DT_UNKNOWN'
# define DT_UNKNOWN     DT_UNKNOWN
                        ^
/home/appstack/libwebsockets/lib/misc/dir.c:172:5: error: 'DT_LNK' is not defined, evaluates to 0 [-Werror,-Wundef]
#if DT_LNK != DT_UNKNOWN
    ^
/usr/include/dirent.h:112:18: note: expanded from macro 'DT_LNK'
# define DT_LNK         DT_LNK
                        ^
/home/appstack/libwebsockets/lib/misc/dir.c:172:15: error: 'DT_UNKNOWN' is not defined, evaluates to 0 [-Werror,-Wundef]
#if DT_LNK != DT_UNKNOWN
              ^
/usr/include/dirent.h:100:21: note: expanded from macro 'DT_UNKNOWN'
# define DT_UNKNOWN     DT_UNKNOWN
                        ^
/home/appstack/libwebsockets/lib/misc/dir.c:180:5: error: 'DT_SOCK' is not defined, evaluates to 0 [-Werror,-Wundef]
#if DT_SOCK != DT_UNKNOWN
    ^
/usr/include/dirent.h:114:18: note: expanded from macro 'DT_SOCK'
# define DT_SOCK        DT_SOCK
                        ^
/home/appstack/libwebsockets/lib/misc/dir.c:180:16: error: 'DT_UNKNOWN' is not defined, evaluates to 0 [-Werror,-Wundef]
#if DT_SOCK != DT_UNKNOWN
               ^
/usr/include/dirent.h:100:21: note: expanded from macro 'DT_UNKNOWN'
# define DT_UNKNOWN     DT_UNKNOWN
                        ^
12 errors generated.
make[2]: *** [lib/CMakeFiles/websockets_shared.dir/build.make:401: lib/CMakeFiles/websockets_shared.dir/misc/dir.c.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:1352: lib/CMakeFiles/websockets_shared.dir/all] Error 2
make: *** [Makefile:163: all] Error 2
```

**Comment by lws-team** [comment]
The CI is on a systemd-nspawn that is running stock 20.04, I also made sure it was up to date with the stock repo, it doesn't make any difference.

> /usr/include/dirent.h:100:21: note: expanded from macro 'DT_UNKNOWN'
> # define DT_UNKNOWN     DT_UNKNOWN

hm inside the 20.04 filesystem, it's like this

```
enum
  {
    DT_UNKNOWN = 0,
# define DT_UNKNOWN     DT_UNKNOWN
...
```

I guess it's a backwards compatibility thing.  But it works out of the box OK here.

What is your compiler?  The CI one is the stock gcc

```
-- The C compiler identification is GNU 9.3.0
```

I think since I am running it OK in CI, you need to look for differences on your end, since you have the symptom and I don't.

**Comment by lws-team** [comment]
... fwiw I also have 20.04 on an RPi4 aarch64 in CI, no problems

https://libwebsockets.org/sai/index.html?task=b4a71b3a59fb213944478a57dd2562b4e0608dd342a8394b4aac65e2268bbdec

**Comment by georgii-ivanov** [comment]
Okay. I was managed to compile source by selecting GCC 9.3.0 as a default compiler.
I don't know which one I had before.
So I guess you can close the issue but just for future reference... it would be useful for other people just check their default compiler used in CMake.

**Comment by lws-team** [comment]
Well, all's well that ends well... the CI is just using stock distro pieces, but if eg you didn't install gcc stuff maybe it does something else.  But there are other CI builds using clang... anyway...

**Comment by orgads** [comment]
It fails when -Wundef is passed. Tested on multiple GCC versions, ranging from 4.1.2 to 10.2.0.

Broke in 886a588963f61045114c3e23512425e0ca20a1bd.

Please reopen.

test.c:
```
enum {
  FOO = 0,
#define FOO FOO
  BAR = 1
#define BAR BAR
};

void func()
{
  int a = FOO;
#if FOO != BAR
  a = BAR;
#endif
}
```

```
$ gcc -Wundef -Werror -c test.c
test.c: In function ‘func’:
test.c:3:13: error: "FOO" is not defined, evaluates to 0 [-Werror=undef]
    3 | #define FOO FOO
      |             ^~~
test.c:11:5: note: in expansion of macro ‘FOO’
   11 | #if FOO != BAR
      |     ^~~
test.c:5:13: error: "BAR" is not defined, evaluates to 0 [-Werror=undef]
    5 | #define BAR BAR
      |             ^~~
test.c:11:12: note: in expansion of macro ‘BAR’
   11 | #if FOO != BAR
      |            ^~~
cc1: all warnings being treated as errors
```

**Comment by lws-team** [comment]
... what is "it" in "it fails"?  Your test app above fails?  What is the toolchain error you see when building lws?

lws doesn't fail to build on 20.04 with whatever cmake options are in force in a variety of scenarios, see, eg,

https://libwebsockets.org/sai/index.html?task=58649f28462406384e0c7242d803d1e88f04438f78bf6563780f144b00e47954

**Comment by orgads** [comment]
I now tested with the real `dirent.h`, and it does succeed with newer GCC. BUT it doesn't work as expected, since the defines are all evaluated to 0 during preprocessing even when they do not fail.

**Comment by lws-team** [comment]
Hmm the CI pieces use lws (and dir.c stuff) built on an actual 20.04 systemd-nspawn, I think it'd fail to basically rm -rf during the CI if it experienced that.

Do I not recall from looking at this when OP posted it, in stock dirent.h there are some nondefault preprocessor conditions to get to this #define X X stuff?

**Comment by orgads** [comment]
This is how it looks:
```
#ifdef __USE_BSD /* This is __USE_MISC in newer glibc */
/* File types for `d_type'.  */
enum
  {
    DT_UNKNOWN = 0,
# define DT_UNKNOWN     DT_UNKNOWN
    DT_FIFO = 1,
# define DT_FIFO        DT_FIFO
    DT_CHR = 2,
# define DT_CHR         DT_CHR
...
 }
#endif
```

Now when you check during preprocessing: `#if DT_FIFO != DT_UNKNOWN` it will *never* be satisfied, since during preprocessing both are defined to an unknown symbol, which in the "good" case resolves to 0 for both.

I'll post a PR soon.

**Comment by lws-team** [comment]
Yeah but who set `__USE_BSD`?  Without that, no funny #defines IIRC

**Comment by orgads** [comment]
It is defined if `_GNU_SOURCE` is defined. Not sure where that comes from though.

**Comment by orgads** [comment]
But if they are not defined at all, it's still invalid to compare them.

**Comment by lws-team** [comment]
No I think they are enums without that IIRC

lws might be triggering the problem if it's GNU_SOURCE, it is defined in some places.

**Comment by orgads** [comment]
But enums cannot be checked by the preprocessor!

**Comment by lws-team** [comment]
Hum... well, let's see what happens with ypur patch on CI across all the platforms.

**Comment by lws-team** [comment]
Generally it seemed happy, but on mingw32 / 64... 

```
ome/sai-ugh-rpm-needs-this-long-path/jobs/0-2.0/libwebsockets/lib/misc/dir.c: In function 'lws_dir':
/home/sai-ugh-rpm-needs-this-long-path/jobs/0-2.0/libwebsockets/lib/misc/dir.c:151:36: error: comparison is always false due to limited range of data type [-Werror=type-limits]
151 | if (DT_BLK != DT_UNKNOWN && type == DT_BLK)
| ^~
/home/sai-ugh-rpm-needs-this-long-path/jobs/0-2.0/libwebsockets/lib/misc/dir.c:153:41: error: comparison is always false due to limited range of data type [-Werror=type-limits]
153 | else if (DT_CHR != DT_UNKNOWN && type == DT_CHR)
| ^~
/home/sai-ugh-rpm-needs-this-long-path/jobs/0-2.0/libwebsockets/lib/misc/dir.c:155:41: error: comparison is always false due to limited range of data type [-Werror=type-limits]
155 | else if (DT_DIR != DT_UNKNOWN && type == DT_DIR)
| ^~
/home/sai-ugh-rpm-needs-this-long-path/jobs/0-2.0/libwebsockets/lib/misc/dir.c:157:42: error: comparison is always false due to limited range of data type [-Werror=type-limits]
157 | else if (DT_FIFO != DT_UNKNOWN && type == DT_FIFO)
| ^~
/home/sai-ugh-rpm-needs-this-long-path/jobs/0-2.0/libwebsockets/lib/misc/dir.c:161:41: error: comparison is always false due to limited range of data type [-Werror=type-limits]
161 | else if (DT_REG != DT_UNKNOWN && type == DT_REG)
| ^~
cc1: all warnings being treated as errors
gmake[2]: *** [lib/CMakeFiles/websockets_shared.dir/build.make:462: lib/CMakeFiles/websockets_shared.dir/misc/dir.c.obj] Error 1
gmake[1]: *** [CMakeFiles/Makefile2:1370: lib/CMakeFiles/websockets_shared.dir/all] Error 2
gmake: *** [Makefile:183: all] Error 2
```

... I changed the type of `type` to unsigned int, that seems to have solved it

**Comment by orgads** [comment]
Thank you. Can you backport also to 4.1?
