### ISSUE TITLE
Build fails with static OpenSSL 1.1.1b

### ISSUE THREAD

**Issue by vaind** [warmcat/libwebsockets#1590]
Follow up from https://github.com/warmcat/libwebsockets/issues/1578#issuecomment-494004249

With shared libraries (without `no-shared` in OpenSSL config call), it works fine. With static, not so much. Steps to reproduce:

```bash
cd /tmp
git clone https://github.com/openssl/openssl.git
cd openssl
git reset --hard OpenSSL_1_1_1b
./config no-shared
make -j

cd /tmp
git clone https://github.com/warmcat/libwebsockets.git
cd libwebsockets
mkdir bb && cd bb
cmake .. -DLWS_OPENSSL_INCLUDE_DIRS=/tmp/openssl/include/ -DLWS_OPENSSL_LIBRARIES="/tmp/openssl/libssl.a;/tmp/openssl/libcrypto.a"
make -j
```

results in 
```
/tmp/libwebsockets/lib/tls/openssl/openssl-client.c:428:3: error: implicit declaration of function 'EVP_MD_CTX_destroy' is invalid in C99 [-Werror,-Wimplicit-function-declaration]
                EVP_MD_CTX_destroy(mdctx);
                ^
/tmp/openssl/include/openssl/evp.h:539:34: note: expanded from macro 'EVP_MD_CTX_destroy'
# define EVP_MD_CTX_destroy(ctx) EVP_MD_CTX_free((ctx))
                                 ^
/tmp/libwebsockets/lib/tls/private.h:84:29: note: expanded from macro 'EVP_MD_CTX_free'
    #define EVP_MD_CTX_free EVP_MD_CTX_destroy
                            ^
/tmp/libwebsockets/lib/tls/openssl/openssl-client.c:474:2: error: implicit declaration of function 'EVP_MD_CTX_destroy' is invalid in C99 [-Werror,-Wimplicit-function-declaration]
        EVP_MD_CTX_destroy(mdctx);
        ^
/tmp/openssl/include/openssl/evp.h:539:34: note: expanded from macro 'EVP_MD_CTX_destroy'
# define EVP_MD_CTX_destroy(ctx) EVP_MD_CTX_free((ctx))
                                 ^
/tmp/libwebsockets/lib/tls/private.h:84:29: note: expanded from macro 'EVP_MD_CTX_free'
    #define EVP_MD_CTX_free EVP_MD_CTX_destroy
                            ^
2 errors generated.
make[2]: *** [CMakeFiles/websockets.dir/build.make:726: CMakeFiles/websockets.dir/lib/tls/openssl/openssl-client.c.o] Error 1
make[2]: *** Waiting for unfinished jobs....
/tmp/libwebsockets/lib/tls/openssl/openssl-client.c:428:3: error: implicit declaration of function 'EVP_MD_CTX_destroy' is invalid in C99 [-Werror,-Wimplicit-function-declaration]
                EVP_MD_CTX_destroy(mdctx);
                ^
/tmp/openssl/include/openssl/evp.h:539:34: note: expanded from macro 'EVP_MD_CTX_destroy'
# define EVP_MD_CTX_destroy(ctx) EVP_MD_CTX_free((ctx))
                                 ^
/tmp/libwebsockets/lib/tls/private.h:84:29: note: expanded from macro 'EVP_MD_CTX_free'
    #define EVP_MD_CTX_free EVP_MD_CTX_destroy
                            ^
/tmp/libwebsockets/lib/tls/openssl/openssl-server.c:414:38: error: incomplete definition of type 'struct ssl_ctx_st'
        x = sk_X509_value(vhost->tls.ssl_ctx->extra_certs, 0);
                          ~~~~~~~~~~~~~~~~~~^
/tmp/openssl/include/openssl/ossl_typ.h:148:16: note: forward declaration of 'struct ssl_ctx_st'
typedef struct ssl_ctx_st SSL_CTX;
               ^
1 error generated.
make[2]: *** [CMakeFiles/websockets_shared.dir/build.make:700: CMakeFiles/websockets_shared.dir/lib/tls/openssl/openssl-server.c.o] Error 1
make[2]: *** Waiting for unfinished jobs....
/tmp/libwebsockets/lib/tls/openssl/openssl-client.c:474:2: error: implicit declaration of function 'EVP_MD_CTX_destroy' is invalid in C99 [-Werror,-Wimplicit-function-declaration]
        EVP_MD_CTX_destroy(mdctx);
        ^
/tmp/openssl/include/openssl/evp.h:539:34: note: expanded from macro 'EVP_MD_CTX_destroy'
# define EVP_MD_CTX_destroy(ctx) EVP_MD_CTX_free((ctx))
                                 ^
/tmp/libwebsockets/lib/tls/private.h:84:29: note: expanded from macro 'EVP_MD_CTX_free'
    #define EVP_MD_CTX_free EVP_MD_CTX_destroy
                            ^
2 errors generated.
make[2]: *** [CMakeFiles/websockets_shared.dir/build.make:726: CMakeFiles/websockets_shared.dir/lib/tls/openssl/openssl-client.c.o] Error 1
/tmp/libwebsockets/lib/tls/openssl/openssl-server.c:414:38: error: incomplete definition of type 'struct ssl_ctx_st'
        x = sk_X509_value(vhost->tls.ssl_ctx->extra_certs, 0);
                          ~~~~~~~~~~~~~~~~~~^
/tmp/openssl/include/openssl/ossl_typ.h:148:16: note: forward declaration of 'struct ssl_ctx_st'
typedef struct ssl_ctx_st SSL_CTX;
               ^
1 error generated.
make[2]: *** [CMakeFiles/websockets.dir/build.make:700: CMakeFiles/websockets.dir/lib/tls/openssl/openssl-server.c.o] Error 1

```

**Comment by lws-team** [comment]
Well... again it works fine with 1.1.1b on Fedora 30, and that builds both shared and static lws by default.  Of course, when the Fedora 30 OpenSSL was built, it built both shared and static, ie, not no-shared.

What's happening is on unix without the openssl .so bringing it in, the cmake test for the related api fails for lack of -ldl.  I pushed a patch to force -ldl for the tests and that should solve it.

**Comment by vaind** [comment]
Yes, the problem is specifically with "no-shared", i.e. static only build of OpenSSL.

The latest master still doesn't build fully.

```
[ 97%] Built target websockets_shared
[ 97%] Linking C executable bin/libwebsockets-test-lejp
[ 97%] Built target test-lejp
[ 98%] Linking C executable bin/libwebsockets-test-client
[ 99%] Linking C executable bin/libwebsockets-test-server
[100%] Linking C executable bin/libwebsockets-test-server-extpoll
/usr/bin/ld: /tmp/openssl/libcrypto.a(dso_dlfcn.o): in function `dlfcn_load':
dso_dlfcn.c:(.text+0x45): undefined reference to `dlopen'
/usr/bin/ld: dso_dlfcn.c:(.text+0xbc): undefined reference to `dlerror'
/usr/bin/ld: dso_dlfcn.c:(.text+0x12e): undefined reference to `dlclose'
/usr/bin/ld: /tmp/openssl/libcrypto.a(dso_dlfcn.o): in function `dlfcn_unload':
dso_dlfcn.c:(.text+0x171): undefined reference to `dlclose'
/usr/bin/ld: /tmp/openssl/libcrypto.a(dso_dlfcn.o): in function `dlfcn_bind_func':
dso_dlfcn.c:(.text+0x224): undefined reference to `dlsym'
/usr/bin/ld: dso_dlfcn.c:(.text+0x2be): undefined reference to `dlerror'
/usr/bin/ld: /tmp/openssl/libcrypto.a(dso_dlfcn.o): in function `dlfcn_pathbyaddr':
dso_dlfcn.c:(.text+0x5a0): undefined reference to `dladdr'
/usr/bin/ld: dso_dlfcn.c:(.text+0x5ed): undefined reference to `dlerror'
/usr/bin/ld: /tmp/openssl/libcrypto.a(dso_dlfcn.o): in function `dlfcn_globallookup':
dso_dlfcn.c:(.text+0x64f): undefined reference to `dlopen'
/usr/bin/ld: dso_dlfcn.c:(.text+0x662): undefined reference to `dlsym'
/usr/bin/ld: dso_dlfcn.c:(.text+0x66d): undefined reference to `dlclose'
clang-8: error: linker command failed with exit code 1 (use -v to see invocation)
make[2]: *** [CMakeFiles/test-client.dir/build.make:87: bin/libwebsockets-test-client] Error 1
make[1]: *** [CMakeFiles/Makefile2:253: CMakeFiles/test-client.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
/usr/bin/ld: /tmp/openssl/libcrypto.a(dso_dlfcn.o): in function `dlfcn_load':
dso_dlfcn.c:(.text+0x45): undefined reference to `dlopen'
/usr/bin/ld: dso_dlfcn.c:(.text+0xbc): undefined reference to `dlerror'
/usr/bin/ld: dso_dlfcn.c:(.text+0x12e): undefined reference to `dlclose'
/usr/bin/ld: /tmp/openssl/libcrypto.a(dso_dlfcn.o): in function `dlfcn_unload':
dso_dlfcn.c:(.text+0x171): undefined reference to `dlclose'
/usr/bin/ld: /tmp/openssl/libcrypto.a(dso_dlfcn.o): in function `dlfcn_bind_func':
dso_dlfcn.c:(.text+0x224): undefined reference to `dlsym'
/usr/bin/ld: dso_dlfcn.c:(.text+0x2be): undefined reference to `dlerror'
/usr/bin/ld: /tmp/openssl/libcrypto.a(dso_dlfcn.o): in function `dlfcn_pathbyaddr':
dso_dlfcn.c:(.text+0x5a0): undefined reference to `dladdr'
/usr/bin/ld: /usr/bin/lddso_dlfcn.c:: (.text+0x5ed): undefined reference to `dlerror'
/tmp/openssl/libcrypto.a(dso_dlfcn.o)/usr/bin/ld: in function `: dlfcn_load/tmp/openssl/libcrypto.a(dso_dlfcn.o)':
: in function `dso_dlfcn.c:dlfcn_globallookup(':
.textdso_dlfcn.c:+0x(.text+0x64f): undefined reference to `45dlopen)'
: undefined reference to `/usr/bin/lddlopen: '
dso_dlfcn.c:(/usr/bin/ld.text: +0xdso_dlfcn.c:662().text: undefined reference to `+0xdlsymbc'
): undefined reference to `/usr/bin/lddlerror: '
dso_dlfcn.c:/usr/bin/ld(: .textdso_dlfcn.c:+0x(66d.text)+0x: undefined reference to `12edlclose)'
: undefined reference to `dlclose'
/usr/bin/ld: /tmp/openssl/libcrypto.a(dso_dlfcn.o): in function `dlfcn_unload':
dso_dlfcn.c:(.text+0x171): undefined reference to `dlclose'
/usr/bin/ld: /tmp/openssl/libcrypto.a(dso_dlfcn.o): in function `dlfcn_bind_func':
dso_dlfcn.c:(.text+0x224): undefined reference to `dlsym'
/usr/bin/ld: dso_dlfcn.c:(.text+0x2be): undefined reference to `dlerror'
/usr/bin/ld: /tmp/openssl/libcrypto.a(dso_dlfcn.o): in function `dlfcn_pathbyaddr':
dso_dlfcn.c:(.text+0x5a0): undefined reference to `dladdr'
/usr/bin/ld: dso_dlfcn.c:(.text+0x5ed): undefined reference to `dlerror'
/usr/bin/ld: /tmp/openssl/libcrypto.a(dso_dlfcn.o): in function `dlfcn_globallookup':
dso_dlfcn.c:(.text+0x64f): undefined reference to `dlopen'
/usr/bin/ld: dso_dlfcn.c:(.text+0x662): undefined reference to `dlsym'
/usr/bin/ld: dso_dlfcn.c:(.text+0x66d): undefined reference to `dlclose'
clang-8: error: linker command failed with exit code 1 (use -v to see invocation)
clang-8: error: linker command failed with exit code 1 (use -v to see invocation)
make[2]: *** [CMakeFiles/test-server-extpoll.dir/build.make:87: bin/libwebsockets-test-server-extpoll] Error 1
make[2]: *** [CMakeFiles/test-server.dir/build.make:87: bin/libwebsockets-test-server] Error 1
make[1]: *** [CMakeFiles/Makefile2:179: CMakeFiles/test-server.dir/all] Error 2
make[1]: *** [CMakeFiles/Makefile2:216: CMakeFiles/test-server-extpoll.dir/all] Error 2
make: *** [Makefile:152: all] Error 2
```

**Comment by lws-team** [comment]
Thanks... yes the test apps also need -ldl then... I amended and repushed the patch.

**Comment by vaind** [comment]
looks good now, thanks
