### ISSUE TITLE
Can not to compile sample

### ISSUE THREAD

**Issue by l41lt0n** [warmcat/libwebsockets#1190]
Hi,

I am trying to compile a sample but I got this problem:

clang -lpthread -Wall -s -o2 main.c -o test-server -lwebsockets -I../build/include -I/usr/local/opt/openssl/include -L../build/lib
ld: warning: option -s is obsolete and being ignored
Undefined symbols for architecture x86_64:
  "_callback_dumb_increment", referenced from:
      _protocols in main-5d3ece.o
  "_callback_http", referenced from:
      _protocols in main-5d3ece.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)

Any suggestion?

**Comment by lws-team** [comment]
> main.c

You're not actually building the lws test code.

It looks like you tried to chop down the test server, which is not a bad thing, but you only removed half the stuff and left in references to what you removed.  You'll need to chop out stuff until what is left can build on its own.

**Comment by l41lt0n** [comment]
What is correctly way to build a simple websocket server?

**Comment by lws-team** [comment]
Cut down the sample in a way where it's not broken?
