### ISSUE TITLE
cross compile in branch v2.4-stable failed if LWS_BUILTIN_GETIFADDRS is defined

### ISSUE THREAD

**Issue by aSebastianMueller** [warmcat/libwebsockets#1068]
[  2%] Building C object CMakeFiles/websockets.dir/lib/misc/base64-decode.c.o
In file included from /projects/src/ext/libwebsockets/lib/misc/base64-decode.c:43:0:
/projects/ext/libwebsockets/lib/private-libwebsockets.h:190:25: fatal error: getifaddrs.h: No such file or directory
compilation terminated.
make[4]: *** [CMakeFiles/websockets.dir/lib/misc/base64-decode.c.o] Error 1

The folder libwebsockets/lib/misc seems to be not in include path.
Is it possible to modify the build process that no additional include path must be set in cmake file when cross compiling for platforms that does not support getifaddrs?

**Comment by lws-team** [comment]
Does this help?

```
diff --git a/lib/misc/getifaddrs.c b/lib/misc/getifaddrs.c
index 4f42ab45..5f68ed2d 100644
--- a/lib/misc/getifaddrs.c
+++ b/lib/misc/getifaddrs.c
@@ -57,7 +57,7 @@
 #define max(a, b) ((a) > (b) ? (a) : (b))
 #endif
 
-#include "getifaddrs.h"
+#include "./misc/getifaddrs.h"
 
 static int
 getifaddrs2(struct ifaddrs **ifap, int af, int siocgifconf, int siocgifflags,
```

**Comment by aSebastianMueller** [comment]
Not in getifaddrs.c.  The error is in /private-libwebsockets.h:190

This works for me:
--- /tmp/tCkicF_private-libwebsockets.h
+++ /projects/ext/libwebsockets/lib/private-libwebsockets.h
@@ -187,7 +187,7 @@
 #include <hubbub/parser.h>
 #endif
 #if defined(LWS_BUILTIN_GETIFADDRS)
- #include <getifaddrs.h>
+#include "./misc/getifaddrs.h"
 #else
  #if !defined(LWS_WITH_ESP8266) && !defined(LWS_WITH_ESP32)
  #if defined(__HAIKU__)

**Comment by lws-team** [comment]
Thanks... I pushed your patch on master + v2.4-stable
